// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PlusgrowWms.Api.Data;

#nullable disable

namespace PlusgrowWms.Api.Migrations
{
    [DbContext(typeof(PlusgrowDbContext))]
    [Migration("20260619070000_AddPickedLocationToSalesOrderItems")]
    partial class AddPickedLocationToSalesOrderItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
